import type { Metadata } from "next";
import { Urbanist } from "next/font/google";
import "./globals.css";
import { twMerge } from "tailwind-merge";

const urbanist = Urbanist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "SparkShift",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={twMerge(urbanist.className, "antialiased bg-black")}>
        {children}
      </body>
    </html>
  );
}
